version: '3.5'
services:

  api:
    image: "node:8"
    container_name: nest-api
    working_dir: /var/www/api
    restart: always
    links:
      - "db:postgres"
    ports:
      - "3000:3000"
    expose:
      - "3000"
    command: "npm run start:dev"
    depends_on:
      - db
      - pgadmin
    volumes:
      - ./api:/var/www/api
    env_file:
      - .env
    networks:
      - default
      - postgres
  db:
    image: postgres:latest
    container_name: db
    hostname: db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
